# Generated by Django 3.0.4 on 2020-10-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20200418_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='percentage_value',
            field=models.PositiveIntegerField(default=70),
        ),
    ]
